name: Generate 3D Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"  # Cada d√≠a
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: Smith-Sr
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "update profile 3d contrib" || exit 0
          git push
